#!/usr/bin/env zsh

# description: When you’re releasing several times a day with automation that is trigger by the tag.

tag=$(git describe --tags --abbrev=0)

patch=$(echo "$tag" | grep -o '[0-9]*$')
prefix=${tag%$patch}

next_patch=$(( $patch + 1))
next_tag="$prefix$next_patch"

echo "$tag -> $next_tag - press enter to tag and push"

read

git tag $next_tag
git push origin $next_tag