#!/usr/bin/env zsh

# description: Smart unarchiver.


file=$1

if [ -f $file ] ; then
    case "$file" in
        *.tar.bz2)      tar xjf $1      ;;
        *.tar.gz)       tar xfv $1      ;;
        *.bz2)          bunzip2 $1      ;;
        *.rar)          unrar x $1      ;;
        *.gz)           gunzip $1       ;;
        *.tar)          tar xf $1       ;;
        *.tbz2)         tar xjf $1      ;;
        *.tgz)          tar xzf $1      ;;
        *.zip)          unzip $1        ;;
        *.Z)            uncompress $1   ;;
        *.7z)           7z x $1         ;;
        *)              echo "'$file' cannot be extracted via ex()" ;;
    esac
else
    echo "'$file' is not a valid file"
fi